server:
  port: 9091
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost:3306/erpproject
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
    
  mail:
    host: smtp.gmail.com
    port: 587
    username: muppuri47@gmail.com
    password: yhld ylmm ccgw nwph
    properties:
      mail:
        smtp:
          starttls:
            enable: true  
    
        
        